/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package testunitaire;

import java.util.Random;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        d20();

    }

    public static void d20(){
        Random d20 = new Random();
        System.out.println(d20.nextInt(19)+1);
    }
}
