/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package rpgtdd;

import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Scanner scan = new Scanner(System.in);

        Character char1 = new Character(500, "Sonic");

        Character char2 = new Character(500, "Shadow");

        
    }
}
